indent Lines 51-58

diff --git a/roles/usb_lib/templates/mount.d/70-usb-library.j2 b/roles/usb_lib/templates/mount.d/70-usb-library.j2
--- a/roles/usb_lib/templates/mount.d/70-usb-library.j2
+++ b/roles/usb_lib/templates/mount.d/70-usb-library.j2
@@ -48,14 +48,14 @@ fi
 # umask mount options.
 # Make the mount root writable by the web server without changing its contents.
 case "$UM_FILESYSTEM" in
-ext2|ext3|ext4|btrfs|xfs|f2fs)
-    logger -t "usb_lib (70-usb-library)" "Making $UM_FILESYSTEM mount root writable by {{ apache_user }}"
-    if ! chown "{{ apache_user }}:{{ apache_user }}" "$UM_MOUNTPOINT" ||
-       ! chmod u+rwx "$UM_MOUNTPOINT"; then
-        logger -t "usb_lib (70-usb-library)" "ERROR: Unable to make $UM_MOUNTPOINT writable by {{ apache_user }}"
-        exit 1
-    fi
-    ;;
+    ext2|ext3|ext4|btrfs|xfs|f2fs)
+        logger -t "usb_lib (70-usb-library)" "Making $UM_FILESYSTEM mount root writable by {{ apache_user }}"
+        if ! chown "{{ apache_user }}:{{ apache_user }}" "$UM_MOUNTPOINT" ||
+        ! chmod u+rwx "$UM_MOUNTPOINT"; then
+            logger -t "usb_lib (70-usb-library)" "ERROR: Unable to make $UM_MOUNTPOINT writable by {{ apache_user }}"
+            exit 1
+        fi
+        ;;
 esac
 {% endif %}
 
